---
# tasks file for nginx
- name: Install the EPEL repo
  yum: name=epel-release state=present
- name: Install nginx
  yum: name=nginx state=present
- name: Deploy the configuration file
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
- name: Upload the web files
  copy:
    src: usr/share/www/html/
    dest: /usr/share/www/html/
- name: Start and enable Nginx
  service: name=nginx state=started enabled=yes