---
# tasks file for mongodb
- include_vars: secrets.yml
- name: Installing mongodb
  apt:
    name: mongodb
    state: present
- name: Start and enable the engine
  service:
    name: mongodb
    state: started
    enabled: yes
- name: Configure Mongodb to accept outside connections
  lineinfile:
    path: /etc/mongodb.conf
    regexp: '^#?bind_ip = 127.0.0.1'
    line: '#bind_ip = 127.0.0.1'
  notify:
     - restart mongodb
- name: Install Python pip
  apt:
    name: python-pip
    state: present
- name: Install pymongo package
  pip:
    name: pymongo
    state: present
- name: Is authentiaction enabled?
  command: grep "^auth = true" /etc/mongodb.conf
  register: auth
  ignore_errors: yes
- name: Add an administrator to the db
  mongodb_user:
    database: admin
    name: root
    password: "{{ dbpass }}"
    roles: root
    state: present
  when: auth.rc == 1
- name: Enable authentication
  lineinfile:
    path: /etc/mongodb.conf
    regexp: '^#?auth \= true'
    line: 'auth = true'
  notify:
    - restart mongodb
- name: Create the application user
  mongodb_user:
    login_user: root
    login_password: "{{ dbpass }}"
    name: "{{ appdbuser }}"
    password: "{{ appdbpass }}"
    database: "{{ dbname }}"
    roles: dbOwner
    state: present
